name: Build-Test-Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-test-unit:
    runs-on: ubuntu-latest

    steps:
    - name: Ceckout GIT repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM packages
      run: npm install
    - name: Run UNIT tests
      run: npm run test:unit
    - name: Display Softuni USERNAME
      run: echo "vidrax"

  build-test-ui:
    needs: build-test-unit
    runs-on: ubuntu-latest

    steps:
    - name: Ceckout GIT repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM packages
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Start application in background mode
      run: npm run start &
    - name: Run UI tests
      run: npm run test:ui

  deploy-app:
    if: github.ref == 'refs/heads/main'
    needs: build-test-ui
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_TOKEN }}
          api-key: ${{ secrets.RENDER_KEY }}
